#!/bin/bash

# ----------------------------------------------------------------------
# This script is intended to be "sourced" by other scripts.
#
#   The script doing the "source" must have set the variable:
#     username_files
#   to an array of files from which to obtain usernames
#
# This script:
#   Set the variable   usernames   to the usernames associated
#   with repositories used in subsequent scripts.
#
#
# Author:  David Mutchler.
# ----------------------------------------------------------------------

if [ "${username_files}" == "" ]; then
    echo ""
    echo "The script that SOURCED this script"
    echo "failed to set the array variable"
    echo "  username_files"
    echo "to a non-empty value."
    echo "EXITING NOW, NOTHING DONE."
    echo ""
    exit 1
fi

# ----------------------------------------------------------------------
# Check that the initial setup for this course and term is OK.
#   At the same time, get the values of the variables:
#      data_folder        e.g.    DATA/DATA-csse120-202030
#      data_subfolders    e.g.  ( DATA   DATA-csse120-202030 )
#
# from the relevant files.
# ----------------------------------------------------------------------

if [ "${CHECK_SETUP_HAS_RUN}" != "1" ]; then
    source SCRIPT-1a-check-setup
fi

# ---------------------------------------------------------------------
# Get the usernames from the specified files in the DATA folder.
# Set the variable   usernames   to those usernames.
# ---------------------------------------------------------------------

cd ${data_folder}

usernames=()
for file in ${username_files[@]}; do
    usernames=( ${usernames[@]} $(< ${file}) )
done

for folder in ${data_subfolders[@]}; do
   cd ..
done

GET_USERNAMES_HAS_RUN=1  # For use in scripts "sourcing" this script.
